#AWSTemplateFormatVersion: '2015-04-27'
Description: Creates an EKS cluster using an IAM role with OIDC to authenticate to AWS, and with a condition that allows only clusters with names starting with a specific string.

Parameters:
  GitHubOrg:
    Description: Name of GitHub organization/user (case sensitive)
    Type: String
    Default: "nailabx"
  RepositoryName:
    Description: Name of GitHub repository (case sensitive)
    Type: String
    Default: "*"
  TagNamePrefix:
    Description: Prefix that must be used for all EKS cluster names
    Type: String
    Default: "test"
  OIDCAudience:
    Description: Audience supplied to configure-aws-credentials.
    Default: "sts.amazonaws.com"
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ""
    Type: String
  RoleName:
    Type: String
    Description: Name the Role
    Default: "GithubAccessTest"

Conditions:
  CreateProvider: !Equals
    - !Ref OIDCProviderArn
    - ""

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
        - !Sub https://github.com/${GitHubOrg}/${RepositoryName}
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
        - Key: Name
          Value: !Sub ${RoleName}-OIDC-Provider

  # Create an IAM role for GitHub Actions to assume
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Federated: !If
              - CreateProvider
              - !Ref GitHubOIDCProvider
              - !Ref OIDCProviderArn
#            Federated:
#              Fn::GetAtt: GitHubOIDCProvider.Arn
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              token.actions.githubusercontent.com:aud: !Ref OIDCAudience
            StringLike:
              token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*

  # Attach a policy to the IAM role that gives it permission to create EKS clusters
  GitHubActionsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GitHubActionsPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: "*"
          Resource: "*"
          Condition:
            StringLike:
              "aws:ResourceTag/Env": !Sub "*${TagNamePrefix}*"
      Roles:
        - !Ref GitHubActionsRole


Outputs:
  GitHubActionsRoleArn:
    Description: ARN of the IAM role
    Value: !Ref GitHubActionsRole



